### ISSUE TITLE
Feature Request: Add reminder that Coffee is old after a certain time has lapsed.

### ISSUE THREAD

**Issue by BHoTasktop** [ehossack/taskpot#1]
It is very dangerous to consume out dated coffee, anything beyond 30 min is just gross. Taskpot should have strong mechanism to guard against user from performing such activity. 

AC: User does not consume more than 30 minutes old coffee.
Behaviour Proposal:
Taskbot should throw a warning when the time has lapsed for coffee to be consumed.

Consideration:
* How would taskbot know if there are still coffee left to be consumed? Potential blocker of the task.
* ADCSS (Automatic Discarded Coffee Syncing System) We need to sync the outdated coffee either to a drain or something. (Window?)

**Comment by ehossack** [comment]
For your second consideration I don't think there's currently a way of solving this. Unless we break a hole in the window.

I think the first issue is definitely a real concern. However, I would propose we solve this by sending a "ghost" or silent notification to the original user who posted the taskpot timer. After 20 minutes, we could ask them if taskpot is drunk, if they click "yes" there will be no notification, if they click no, it will remind the channel stale coffee must be drunk (or if 1 minute elapses).

How does this sound?

**Comment by BHoTasktop** [comment]
hey, sorry about the late reply. It has been a busy day at work, I am sure you have similar experiences at your place of work. I like the idea of having hole in windows. Holes are also known to make things go faster.  I also like the second proposal. We should also add a count down so that within the 9-10 minute window the drinkers will be constantly reminded that there is coffee and then properly update the state of the pot.  (fresh coffee->stale coffee) or (fresh coffee->empty coffee). Bot should also have a query capability to understand the last state of the pot. Which will be beneficial since all interaction is just changing the state of the pot.

**Comment by BHoTasktop** [comment]
Should I file another Feature Request first to make tasktbot do state tracking?

**Comment by ehossack** [comment]
So to clarify here, we have two proposed items:

1. Prompt the timer-setting user about taskpot state
2. Warn channel wide about 'stale' coffee

**Comment by BHoTasktop** [comment]
sound about right, we don't want to know when the coffee was drank yah?

**Comment by ehossack** [comment]
Resolved in e0a9bbc3cee19843eddf0d2563e174ea79ef2e7e
