### ISSUE TITLE
giphy api should exclude NSFW gifs

### ISSUE THREAD

**Issue by ehossack** [ehossack/taskpot#9]
Currently it's any rating

**Comment by ehossack** [comment]
@sminto

**Comment by ehossack** [comment]
cba598589e1a94dcebf90c5d927f99986121daba

I hope this will not _only_ return pg-13 gifs. Just restrict to a maximum of pg-13.
Couldn't actually determine this from the official Giphy api docs, https://developers.giphy.com/docs/
so fingers crossed.

**Comment by sminto** [comment]
Thanks!  It seems that should be OK based on

https://github.com/Giphy/GiphyAPI/issues/55

**Comment by ehossack** [comment]
I'm adjusting this down a level. Still some questionable gifs.

**Comment by ehossack** [comment]
e31838e
